# Pre-commit hooks for LLM Token Manager
# Simplified and fast configuration for solo developer workflow
#
# Setup: pip install pre-commit && pre-commit install
# Skip hooks for urgent commits: git commit --no-verify

repos:
  # Basic file checks (fast)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-merge-conflict
      - id: detect-private-key

  # Python formatting (fast, auto-fixes)
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        args: [--line-length=88]

  # Import sorting (fast, auto-fixes)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black]

  # Basic linting (fast)
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]

# Skip slow/problematic checks - let CI handle them
# Removed: mypy (slow type checking)
# Removed: bandit (security - CI handles it)
# Removed: pylint (redundant with flake8)

default_language_version:
  python: python3.11

exclude: |
  (?x)^(
      .*/__pycache__/.*|
      .*/.venv/.*|
      .*/venv/.*
  )$
