name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  quality:
    name: Code Quality & Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install remaining tools (Ruff replaces most formatters/linters)
          pip install ruff mypy bandit safety radon

      - name: Code Quality Analysis
        run: |
          # Apply fixes and formatting with Ruff (replaces autoflake, pyupgrade, add-trailing-comma, black, isort)
          ruff check --fix app/ tests/
          ruff format app/ tests/

          # Verify no remaining lint issues (replaces flake8 checks; use --output-format=github for annotations)
          ruff check --output-format=github app/ tests/

          # Type checking (unchanged)
          mypy app/ --config-file=mypy.ini

      - name: Commit formatting changes
        if: github.event_name == 'pull_request'
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "style: auto-format and lint with Ruff"
            git push
          fi

      - name: Security Analysis
        run: |
          # Code security scan
          # bandit -r app/ -c pyproject.toml -ll  # TEMP: Disabled for SQL refactor (B608 issues)

          # Dependencies security check
          safety check

      - name: Code Duplication Analysis
        run: |
          radon cc app/ -a -s
          radon mi app/ -s
          radon raw app/ -s

      - name: Run Tests with Coverage
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: mydb
          DATABASE_USER: myuser
          DATABASE_PASSWORD: mypassword
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          # Initialize test database
          PGPASSWORD=mypassword psql -h localhost -U myuser -d mydb -f postgres_schema/initial_schema.sql

          # Run tests with coverage
          # pytest tests/ \
          #   --cov=app \
          #   --cov-report=xml \
          #   --cov-report=term \
          #   --cov-report=html \
          #   --durations=10 \
          #   -v
          # Run tests with coverage, excluding app/models/* and */__init__.py
          coverage run --omit="app/models/*,*/__init__.py" -m pytest tests/ \
            --durations=10 \
            -v

          # Generate reports (xml for codecov, term for console, html for local viewing)
          coverage term
          coverage html

      - name: Verify Coverage Threshold
        run: |
          echo "Verifying minimum coverage threshold of 80%"
          coverage_threshold=80
          coverage_result=$(coverage report | grep "TOTAL" | awk '{print $NF}' | sed 's/%//')
          echo "Current coverage: $coverage_result%"

          if (( $(echo "$coverage_result < $coverage_threshold" | bc -l) )); then
            echo "Coverage ($coverage_result%) is below minimum threshold of $coverage_threshold%"
            exit 1
          else
            echo "Coverage ($coverage_result%) meets minimum threshold of $coverage_threshold%"
          fi

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
