name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  quality:
    name: Code Quality & Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Code Quality Analysis
        run: |
          # Auto-fix formatting
          black app/ tests/ || true
          isort app/ tests/ || true

          # Check formatting
          black --check --diff app/ tests/
          isort --check --diff app/ tests/

          # Linting
          flake8 app/ tests/ --max-line-length=88 --extend-ignore=E203,W503 --statistics

          # Type checking
          mypy app/ --config-file=mypy.ini || echo "Type checking completed with warnings"

      - name: Security Analysis
        run: |
          # Code security scan
          bandit -r app/ -c pyproject.toml -ll || echo "Security scan completed with warnings"

          # Dependencies security check
          pip install safety
          safety check --ignore 70612 || echo "Dependency check completed with warnings"

      - name: Code Metrics
        run: |
          pip install radon
          echo "Cyclomatic Complexity:"
          radon cc app/ -a -s
          echo "Maintainability Index:"
          radon mi app/ -s

      - name: Run Tests with Coverage
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: mydb
          DATABASE_USER: myuser
          DATABASE_PASSWORD: mypassword
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          # Initialize test database
          PGPASSWORD=mypassword psql -h localhost -U myuser -d mydb -f postgres_schema/initial_schema.sql

          # Run tests with coverage
          pytest tests/ \
            --cov=app \
            --cov-report=xml \
            --cov-report=term \
            --cov-report=html \
            --durations=10 \
            -v

      - name: Verify Coverage Threshold
        run: |
          echo "Verifying minimum coverage threshold of 80%"
          coverage_threshold=80
          coverage_result=$(coverage report | grep "TOTAL" | awk '{print $NF}' | sed 's/%//')
          echo "Current coverage: $coverage_result%"

          if (( $(echo "$coverage_result < $coverage_threshold" | bc -l) )); then
            echo "Coverage ($coverage_result%) is below minimum threshold of $coverage_threshold%"
            exit 1
          else
            echo "Coverage ($coverage_result%) meets minimum threshold of $coverage_threshold%"
          fi

      - name: Upload Coverage Report
        if: always()
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
