name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  quality:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper coverage analysis

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Code Quality Checks
        run: |
          # Format and style
          black --check --diff app/ tests/
          isort --check --diff app/ tests/
          
          # Linting and complexity
          flake8 app/ tests/ \
            --max-line-length=88 \
            --max-complexity=10 \
            --select=E9,F63,F7,F82,C901 \
            --count \
            --statistics
          
          # Type checking
          mypy app/ --config-file=mypy.ini

      - name: Security Scan
        run: |
          # Security vulnerabilities
          bandit -r app/ -c pyproject.toml -ll -ii
          
          # Dependency vulnerabilities
          pip install safety
          safety check

      - name: Run Tests with Coverage
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: mydb
          DATABASE_USER: myuser
          DATABASE_PASSWORD: mypassword
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          # Initialize database schema
          PGPASSWORD=mypassword psql -h localhost -U myuser -d mydb -f postgres_schema/initial_schema.sql
          
          # Run tests with coverage
          pytest tests/ \
            --cov=app \
            --cov-report=xml \
            --cov-report=term \
            --cov-report=html \
            --durations=10 \
            -v

      - name: Check Coverage Threshold
        run: |
          echo "Checking coverage meets minimum 80% threshold..."
          coverage_threshold=80
          coverage_result=$(coverage report | grep "TOTAL" | awk '{print $NF}' | sed 's/%//')
          echo "Current coverage: $coverage_result%"
          
          if (( $(echo "$coverage_result < $coverage_threshold" | bc -l) )); then
            echo "❌ Coverage ($coverage_result%) is below minimum threshold of $coverage_threshold%"
            exit 1
          else
            echo "✅ Coverage ($coverage_result%) meets minimum threshold of $coverage_threshold%"
          fi

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  docker:
    name: Docker Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate and Test Infrastructure
        run: |
          # Validate compose file
          docker-compose config
          
          # Start services
          docker-compose up -d
          
          # Wait for services and check health
          sleep 10
          docker-compose ps
          
          # Test connections
          docker exec llm_postgres pg_isready -U myuser
          docker exec llm_redis redis-cli ping
          
          # Cleanup
          docker-compose down -v